# Generated by Django 2.1.3 on 2018-11-10 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='cards.CardCollection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='grave',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grave', to='cards.CardCollection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hand', to='cards.CardCollection'),
            preserve_default=False,
        ),
    ]
