# Generated by Django 2.1.3 on 2018-11-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20181110_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('setup', 'Setup'), ('busy', 'Busy'), ('done', 'Done')], default='setup', max_length=20),
        ),
    ]
