# Generated by Django 2.1.3 on 2018-11-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20181113_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='phase',
            field=models.CharField(choices=[('draw', 'Draw'), ('main1', 'Main 1'), ('attack', 'Attack'), ('block', 'Block'), ('main2', 'Main 2'), ('upkeep', 'Upkeep')], default='draw', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
