# Generated by Django 2.1.3 on 2018-11-14 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20181113_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('busy', 'Busy'), ('done', 'Done')], max_length=20)),
                ('turn', models.IntegerField()),
                ('round', models.IntegerField()),
                ('phase', models.CharField(choices=[('draw', 'Draw'), ('main', 'Main'), ('attack', 'Attack'), ('block', 'Block'), ('upkeep', 'Upkeep')], max_length=20)),
                ('health1', models.IntegerField()),
                ('health2', models.IntegerField()),
                ('deck1_size', models.IntegerField()),
                ('deck2_size', models.IntegerField()),
                ('hand1_size', models.IntegerField()),
                ('hand2_size', models.IntegerField()),
                ('grave1_size', models.IntegerField()),
                ('grave2_size', models.IntegerField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('command', models.CharField(choices=[('status', 'Status'), ('draw', 'Draw'), ('shuffle', 'Shuffle'), ('phase', 'Phase')], max_length=250)),
                ('outcome', models.CharField(max_length=250)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Player')),
            ],
        ),
        migrations.AlterModelManagers(
            name='gamecard',
            managers=[
                ('deck', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.CharField(choices=[('draw', 'Draw'), ('main', 'Main'), ('attack', 'Attack'), ('block', 'Block'), ('upkeep', 'Upkeep')], default='draw', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Game'),
        ),
        migrations.AddField(
            model_name='event',
            name='gcard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.GameCard'),
        ),
    ]
