# Generated by Django 2.1.3 on 2018-11-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20181114_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_combat_actor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='phase',
            field=models.CharField(choices=[('draw', 'Draw'), ('main', 'Main'), ('combat', 'Combat'), ('upkeep', 'Upkeep')], max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.CharField(choices=[('draw', 'Draw'), ('main', 'Main'), ('combat', 'Combat'), ('upkeep', 'Upkeep')], default='draw', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamecard',
            name='slot',
            field=models.CharField(choices=[('deck', 'Deck'), ('hand', 'Hand'), ('grave', 'Graveyard'), ('table', 'Table')], max_length=10),
        ),
    ]
