# Generated by Django 2.1.3 on 2018-11-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20181113_0508'),
        ('engine', '0007_auto_20181115_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='num',
        ),
        migrations.AddField(
            model_name='event',
            name='ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Ability'),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='tapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='command',
            field=models.CharField(choices=[('status', 'Status'), ('draw', 'Draw'), ('shuffle', 'Shuffle'), ('phase', 'Phase'), ('play', 'Play'), ('cost', 'Cost'), ('benefit', 'Benefit')], max_length=250),
        ),
    ]
