# Generated by Django 2.1.3 on 2018-12-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_auto_20181202_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_turn_person',
            field=models.IntegerField(default=0),
        ),
    ]
