# Generated by Django 2.1.3 on 2018-12-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_player_last_turn_person'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gamecard',
            managers=[
            ],
        ),
    ]
