# Generated by Django 2.1.4 on 2018-12-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_auto_20181206_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecard',
            name='slot',
            field=models.CharField(choices=[('deck', 'Deck'), ('hand', 'Hand'), ('table', 'Table'), ('grave', 'Graveyard')], max_length=10),
        ),
    ]
