# Generated by Django 2.1.3 on 2018-11-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(choices=[('t', 'Tap')], max_length=3)),
                ('benefit', models.CharField(choices=[('m1g', 'Adds 1 generic mana')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('l', 'Land'), ('c', 'Creature')], max_length=1)),
                ('mana', models.IntegerField()),
                ('power', models.IntegerField(null=True)),
                ('toughness', models.IntegerField(null=True)),
                ('abilities', models.ManyToManyField(to='cards.Ability')),
            ],
        ),
        migrations.CreateModel(
            name='CardCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='cards.Card')),
            ],
        ),
    ]
