# Generated by Django 2.1.3 on 2018-11-12 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(choices=[('t', 'Tap')], max_length=3)),
                ('benefit', models.CharField(choices=[('m1g', 'Adds 1 generic mana')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('l', 'Land'), ('c', 'Creature')], max_length=1)),
                ('mana', models.IntegerField()),
                ('power', models.IntegerField(null=True)),
                ('toughness', models.IntegerField(null=True)),
                ('abilities', models.ManyToManyField(to='cards.Ability')),
            ],
        ),
        migrations.CreateModel(
            name='CardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
            ],
            options={
                'ordering': ['pos'],
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('carditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.CardItem')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='engine.Player')),
            ],
            bases=('cards.carditem',),
        ),
        migrations.CreateModel(
            name='Grave',
            fields=[
                ('carditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.CardItem')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grave', to='engine.Player')),
            ],
            bases=('cards.carditem',),
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('carditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.CardItem')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand', to='engine.Player')),
            ],
            bases=('cards.carditem',),
        ),
        migrations.AddField(
            model_name='carditem',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card'),
        ),
    ]
