# Generated by Django 2.1.3 on 2018-12-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20181113_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='toughness',
            new_name='endurance',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='mana',
            new_name='support',
        ),
        migrations.AlterField(
            model_name='card',
            name='kind',
            field=models.CharField(choices=[('person', 'Person'), ('opinion', 'Opinion'), ('paper', 'Paper'), ('evidence', 'Evidence')], max_length=20),
        ),
    ]
