# Generated by Django 2.1.3 on 2018-11-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20181111_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardposition',
            name='col',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpos', to='cards.CardCollection'),
        ),
    ]
